---
title: "Exploratory Analysis"
author: |
    |
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=0.75in
output: 
  pdf_document:
    number_sections: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 120)
```


```{r, echo = FALSE, warning=FALSE, message = FALSE}
library(kableExtra)
library(dplyr)
library(readxl)
library(lubridate)

source("paths.R")
source("estimator.R")
```
# Main Results

```{r, echo = FALSE, warning=FALSE, message = FALSE}
load(file.path(path_staged_data, "dat_analysis.RData"))

# This step might appear unnecessary, but is needed since
# dat_analysis is both a tibble and a data frame
# but code in estimator.R does not work with tibbles
# The call to as.data.frame() has the effect of making
# dat_analysis of class data frame but not of class tibble
dat_analysis <- as.data.frame(dat_analysis)
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt1 -- "No. of participant-decision points excluded due to the fact that participants did not select their preferred Product or Charity at baseline"
cnt1 <- dat_analysis %>% 
  filter(exclude_from_all == 1) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# The software expects that intervention assignment is coded as numeric, 
# and not character type
dat_analysis <- dat_analysis %>% 
  filter(exclude_from_all == 0) %>% 
  mutate(randassign_invite = case_when(
    randassign_invite == "Product" ~ 1,
    randassign_invite == "Charity" ~ 0,
    TRUE ~ NA_real_))
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt2 -- "No. of participant-decision points excluded due to the fact that participants had missing values in any of the covariates utilized in the noise reduction model"
cnt2 <- dat_analysis %>% 
  filter(did_not_report_primary_analysis_vars == 1) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Data preparation steps for primary analysis
these_vars <- c("tot_days_with_any_drinks", 
                "typical_num_drinks_per_day",
                "is_female",
                "is_white_only",
                "days_elapsed_since_entering")

dat_exploratory_analysis <- dat_analysis %>%
  # Drop participants who had any missing data in these_vars
  filter(did_not_report_primary_analysis_vars == 0) %>%
  select(participant_id, 
         decision_point, 
         randassign_invite, 
         coinflip, 
         Y_delta47,
         all_of(these_vars),
         sm_flagged, randtime_invite_hrts,
         SMdrawing_Prod, SMdrawing_Char, Finished)
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt3 -- "No of participant-decision points excluded due to the fact that these participant-decision points came immediately after (i.e., time t+1) a decision point (i.e., time t) where the participant reported heavy drinking and hence were eligible for randomization (i.e., at time t+1). However, these participant-decision points did not have a record of the participant's randomization assignment present in the data."
cnt3 <- dat_exploratory_analysis %>% 
  filter(!(is.na(sm_flagged) & is.na(randtime_invite_hrts))) %>% 
  filter(coinflip == 0) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt4 -- "No. of participant-decision points excluded due to these participant-decision points not having a recorded randomization assignment at participant-decision points in which should have been randomized"
cnt4 <- dat_exploratory_analysis %>% 
  filter(is.na(sm_flagged) & is.na(randtime_invite_hrts)) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
dat_exploratory_analysis <- dat_exploratory_analysis %>%
  mutate(any_alloc = 1*(!is.na(SMdrawing_Prod) & !is.na(SMdrawing_Char)),
         is_equal_alloc = 1*(SMdrawing_Prod==1 & SMdrawing_Char==1),
         is_all_alloc_product = 1*(SMdrawing_Prod==2 & SMdrawing_Char==0),
         is_all_alloc_charity = 1*(SMdrawing_Prod==0 & SMdrawing_Char==2)) %>%
  mutate(is_any_alloc_product = 1*((is_equal_alloc==1) | (is_all_alloc_product)),
         is_any_alloc_charity = 1*((is_equal_alloc==1) | (is_all_alloc_charity)))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
list_dat <- list()

for(idx_participant in unique(dat_exploratory_analysis$participant_id)){
  currdat <- dat_exploratory_analysis %>% 
    filter(participant_id == idx_participant) %>% 
    arrange(decision_point)
  
  laggedvar <- head(currdat[["is_any_alloc_product"]], n=-1)
  laggedvar <- c(NA, laggedvar)
  currdat[["is_any_alloc_product_lag_minus_one"]] <- laggedvar
  
  laggedvar <- head(currdat[["is_any_alloc_charity"]], n=-1)
  laggedvar <- c(NA, laggedvar)
  currdat[["is_any_alloc_charity_lag_minus_one"]] <- laggedvar
  
  laggedvar <- head(currdat[["is_all_alloc_product"]], n=-1)
  laggedvar <- c(NA, laggedvar)
  currdat[["is_all_alloc_product_lag_minus_one"]] <- laggedvar
  
  laggedvar <- head(currdat[["is_all_alloc_charity"]], n=-1)
  laggedvar <- c(NA, laggedvar)
  currdat[["is_all_alloc_charity_lag_minus_one"]] <- laggedvar
  
  laggedvar <- head(currdat[["is_equal_alloc"]], n=-1)
  laggedvar <- c(NA, laggedvar)
  currdat[["is_equal_alloc_lag_minus_one"]] <- laggedvar
  
  laggedvar <- head(currdat[["Finished"]], n=-1)
  laggedvar <- c(NA, laggedvar)
  currdat[["finished_lag_minus_one"]] <- laggedvar
  
  laggedvar <- head(currdat[["randassign_invite"]], n=-1)
  laggedvar <- c(NA, laggedvar)
  currdat[["randassign_invite_lag_minus_one"]] <- laggedvar
  
  laggedvar <- head(currdat[["any_alloc"]], n=-1)
  laggedvar <- c(NA, laggedvar)
  currdat[["any_alloc_lag_minus_one"]] <- laggedvar
  
  list_dat <- append(list_dat, list(currdat))
}

dat_exploratory_analysis <- do.call(rbind, list_dat)
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt5 -- "No. of participant-decision points excluded due to the participant not completing the survey at the previous decision point after having been invited to self-monitor"
cnt5 <- dat_exploratory_analysis %>% 
  filter(decision_point > 1) %>%
  filter(coinflip==1 & finished_lag_minus_one==0) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt5 -- "No. of participant-decision points excluded due to the participant not having been invited to self-monitor at the previous decision point"
cnt6 <- dat_exploratory_analysis %>% 
  filter(decision_point > 1) %>%
  filter(coinflip==1 & is.na(finished_lag_minus_one)) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
dat_exploratory_analysis <- dat_exploratory_analysis %>%
  mutate(use_dp = coinflip) %>%
  # Exclude 1st decision point
  mutate(use_dp = replace(use_dp, decision_point==1, 0)) %>%
  # Exclude decision point if previous survey was begun but not completed
  mutate(use_dp = replace(use_dp, finished_lag_minus_one==0, 0)) %>%
  # Exclude decision point if previous survey was never begun
  mutate(use_dp = replace(use_dp, is.na(finished_lag_minus_one), 0)) %>%
  # Sanity check: 999 should not impact estimates
  mutate(is_equal_alloc_lag_minus_one = replace(is_equal_alloc_lag_minus_one, use_dp==0, 999),
         is_all_alloc_product_lag_minus_one = replace(is_all_alloc_product_lag_minus_one, use_dp==0, 999),
         is_all_alloc_charity_lag_minus_one = replace(is_all_alloc_charity_lag_minus_one, use_dp==0, 999))
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# How many participants and decision points will be used to estimate the treatment effect?
tab_summary_stats <- dat_exploratory_analysis %>%
    filter(use_dp==1) %>%
    group_by(decision_point) %>%
    summarise(count_randomized = n()) %>%
  mutate(excluded = 591 - count_randomized)

colnames(tab_summary_stats) <- c("Decision Point", "Total No. Participants Included in Analysis",  "Total No. Participants Excluded from Analysis")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
tab_summary_stats_alloc_any <- dat_exploratory_analysis %>%
  filter(use_dp==1) %>%
  group_by(decision_point) %>%
  summarise(tot = n(),
            n_prev_any_alloc_performed = sum(any_alloc_lag_minus_one)) %>%
  mutate(pct = (n_prev_any_alloc_performed/tot)*100)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
tab_summary_stats_alloc_type <- dat_exploratory_analysis %>%
  filter(use_dp==1) %>%
  group_by(decision_point) %>%
  summarise(n_prev_alloc_all_prod = sum(is_all_alloc_product_lag_minus_one),
            n_prev_alloc_equal = sum(is_equal_alloc_lag_minus_one),
            n_prev_alloc_all_charity = sum(is_all_alloc_charity_lag_minus_one)) %>%
  mutate(tot = n_prev_alloc_all_prod + n_prev_alloc_equal + n_prev_alloc_all_charity)

tab2_summary_stats_alloc_type <- dat_exploratory_analysis %>%
  filter(use_dp==1) %>%
  group_by(decision_point) %>%
  summarise(n_curr_alloc_all_prod = sum(is_all_alloc_product, na.rm=TRUE),
            n_curr_alloc_equal = sum(is_equal_alloc, na.rm=TRUE),
            n_curr_alloc_all_charity = sum(is_all_alloc_charity, na.rm=TRUE),
            n_none = sum(1*(is.na(is_all_alloc_product)|is.na(is_equal_alloc)|is.na(is_all_alloc_charity)))) %>%
  mutate(tot = n_curr_alloc_all_prod + n_curr_alloc_equal + n_curr_alloc_all_charity + n_none)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
list_results <- binary_outcome_moderated_effect(dta = dat_exploratory_analysis, 
                                                control_var = c("tot_days_with_any_drinks", 
                                                                "typical_num_drinks_per_day", 
                                                                "is_white_only",
                                                                "is_female", 
                                                                "days_elapsed_since_entering"),
                                                moderator = c("is_equal_alloc_lag_minus_one",
                                                              "is_all_alloc_charity_lag_minus_one"),
                                                id_var = "participant_id",
                                                day_var = "decision_point",
                                                trt_var = "randassign_invite",
                                                outcome_var = "Y_delta47",
                                                avail_var = "use_dp",
                                                prob_treatment = 1/2,
                                                significance_level = 0.05)


significance_level <- 0.05
p <- list_results[["dims"]]$p
q <- list_results[["dims"]]$q
n <- list_results[["sample_size"]]
all_estimates <- c(list_results[["alpha_hat"]], list_results[["beta_hat"]])
all_std_err <- c(list_results[["alpha_se_ssa"]], list_results[["beta_se_ssa"]])
test_stat <- all_estimates / all_std_err
critical_value <- qt(1 - significance_level/2, df = n - p - q) # two-sided
p_val <- lapply(test_stat, function(x){
  out <- 2 * pt(abs(x), df = n - p - q, lower.tail = FALSE) # two-sided
  return(out)
})
p_val <- do.call(rbind, p_val)

dat_results <- data.frame(estimate = all_estimates,
                          std_err = all_std_err,
                          p = p_val,
                          LB95 = all_estimates - critical_value*all_std_err,
                          UB95 = all_estimates + critical_value*all_std_err)

dat_results <- round(dat_results, digits = 3)
colnames(dat_results) <- c("est", "SE", "p", "95%CI: LB", "95%CI: UB")
row.names(dat_results) <- c("Intercept", 
                            "No. of Days with any drinks", 
                            "No. of Drinks per day", 
                            "White (1=Yes, 0=otherwise)", 
                            "Female (1=Yes, 0=otherwise)",
                            "No. of Days elapsed since entering",
                            "beta0",
                            "beta1 (Trt x Equal alloc)",
                            "beta2 (Trt x All alloc charity)")

```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
est_beta <- as.matrix(list_results[["beta_hat"]])
est_covmat_beta <- list_results[["varcov_ssa"]][1:p,1:p]

# Calculate contrasts on the risk ratio scale
exp_estimates <- exp(est_beta)

# Calculate 95% CI's of contrasts on the risk ratio scale
Lmat <- matrix(c(1,0,0,
                 1,1,0,
                 1,0,1), byrow = TRUE, nrow = 3)

est_beta <- as.matrix(est_beta)
U <- exp(Lmat %*% est_beta)
U <- c(U)
U <- diag(U)

var_rr <- (U %*% Lmat) %*% est_covmat_beta %*% t(U %*% Lmat)
stderr_rr <- sqrt(diag(var_rr))
rrLB95 <- exp(Lmat %*% est_beta) - critical_value * stderr_rr
rrUB95 <- exp(Lmat %*% est_beta) + critical_value * stderr_rr

# Collect results into a data frame
dat_exp_results <- data.frame(exp_estimates = diag(U),
                              rrLB95 = rrLB95,
                              rrUB95 = rrUB95)
dat_exp_results <- round(dat_exp_results, digits = 3)
colnames(dat_exp_results) <- c("est","95%CI: LB","95%CI: UB")
row.names(dat_exp_results) <- c("Risk Ratio: All points allocated to product",
                                "Risk Ratio: Equal allocation of points to product and charity",
                                "Risk Ratio: All points allocated to charity")
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
kable(tab_summary_stats, format="latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = c("HOLD_position", "scale_down"))

kable(tab_summary_stats_alloc_any, 
      format="latex", 
      booktabs=TRUE, 
      col.names = c("Current Decision Point (j)",
                    "Total No. Participants Included in Analysis",
                    "No. of Participants",
                    "Percent of Participants")) %>%
  add_header_above(c(" "=1, " "=1, "Performed Point Allocation at Previous Decision Point (j-1)" = 2)) %>%
  kable_styling(latex_options = c("HOLD_position", "scale_down"))

kable(tab_summary_stats_alloc_type, 
      format="latex", 
      booktabs=TRUE, 
      col.names = c("Current Decision Point (j)",
                    "Product: 2 Points, Charity: 0 Points",
                    "Product: 1 Point, Charity: 1 Point",
                    "Product: 0 Points, Charity: 2 Points",
                    "Total No. Participants at Current Decision Point (j) Included in Analysis")) %>%
  add_header_above(c(" "=1, "Allocation of Points at Previous Decision Point (j-1)" = 3, " "=1)) %>%
  kable_styling(latex_options = c("HOLD_position", "scale_down"))

kable(tab2_summary_stats_alloc_type, 
      format="latex", 
      booktabs=TRUE, 
      col.names = c("Current Decision Point (j)",
                    "Product: 2 Points, Charity: 0 Points",
                    "Product: 1 Point, Charity: 1 Point",
                    "Product: 0 Points, Charity: 2 Points",
                    "Did not perform point-allocation",
                    "Total No. Participants at Current Decision Point (j) Included in Analysis")) %>%
  add_header_above(c(" "=1, "Allocation of Points at Current Decision Point (j)" = 4, " "=1)) %>%
  kable_styling(latex_options = c("HOLD_position", "scale_down"))

kable(dat_results, format="latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = c("HOLD_position")) %>% 
  pack_rows("Control Covariates", 1, q) %>% 
  pack_rows("Causal", q+1, q+p)

kable(dat_exp_results, format="latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = c("HOLD_position"))
```

\newpage

```{r, echo=FALSE, warning=FALSE, message=FALSE}
par(mar = c(6, 5, 0.75, 0.75) + 0.1)  # Bottom, left, top, right
plot(-1, 
     type="n",
     xlim = c(1,3),
     ylim = c(0.5,1.50),
     xaxt="n",
     yaxt="n",
     xlab = "",
     ylab = "Risk Ratio", 
     cex.lab = 1.75,
     frame.plot = FALSE)
axis(1, at = c(1,2,3), cex.axis = 1.75, lwd = 5, padj = 1, labels = c("","",""))
axis(2, at = seq(0.5,1.5,0.25), cex.axis = 1.75, lwd = 5)

# Draw the x-axis labels.
text(x = 1:3,
     y = par("usr")[3] - 0.15,
     labels = c("Product: 2,\nCharity: 0", "Product: 1,\nCharity: 1", "Product: 0,\nCharity: 2"),
     xpd = NA,
     srt = 35,
     adj = 0.9,
     cex = 1.5)

points(1:3, dat_exp_results$est, pch = 21, col = "cornflowerblue", bg = "cornflowerblue", cex = 4)
segments(x0 = c(1), x1 = c(1), y0 =  dat_exp_results$`95%CI: LB`[1], y1 =  dat_exp_results$`95%CI: UB`[1], lwd = 7, col = "cornflowerblue")
segments(x0 = c(2), x1 = c(2), y0 =  dat_exp_results$`95%CI: LB`[2], y1 =  dat_exp_results$`95%CI: UB`[2], lwd = 7, col = "cornflowerblue")
segments(x0 = c(3), x1 = c(3), y0 =  dat_exp_results$`95%CI: LB`[3], y1 =  dat_exp_results$`95%CI: UB`[3], lwd = 7, col = "cornflowerblue")
abline(h = 1, lty = 1, lwd = 5, col = "black")
```

\newpage

# Appendix: Participants excluded from analyses -- breakdown by decision point and rationale

```{r, echo=FALSE, warning=FALSE, message=FALSE}
cnt1 <- cnt1 %>% filter(decision_point > 1)
cnt2 <- cnt2 %>% filter(decision_point > 1)
cnt3 <- cnt3 %>% filter(decision_point > 1)
cnt4 <- cnt4 %>% filter(decision_point > 1)
cnt5 <- cnt5 %>% filter(decision_point > 1)
cnt6 <- cnt6 %>% filter(decision_point > 1)

colnames(cnt1) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt2) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt3) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt4) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt5) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt6) <- c("Decision Point", "Number of Participants Excluded")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
kable(cnt1, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to the fact that participants did not select their preferred Product or Charity at baseline") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt2, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to the fact that participants had missing values in any of the covariates utilized in the noise reduction model") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt3, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to these participant-decision points not having a recorded randomization assignment at participant-decision points in which should have been randomized") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt4, format="latex", booktabs=TRUE, caption = "No of participant-decision points excluded due to the fact that these participant-decision points came immediately after (i.e., time t+1) a decision point (i.e., time t) where the participant reported heavy drinking and hence were eligible for randomization (i.e., at time t+1). However, these participant-decision points did not have a record of the participant's randomization assignment present in the data.") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt5, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to the participant not completing the survey at the previous decision point after having been invited to self-monitor") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt6, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to the participant not having been invited to self-monitor at the previous decision point. These participants were also not eligible for randomization at the previous decision point. Recall that if participants were not eligible for randomization at a particular decision point, they were not sent a self-monitoring survey at that particular decision point.") %>% 
  kable_styling(latex_options = c("HOLD_position"))
```


