---
title: "Main Analysis"
author: |
    |
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
output: 
  pdf_document:
    number_sections: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width = 120)
```


```{r, echo = FALSE, warning=FALSE, message = FALSE}
library(kableExtra)
library(dplyr)
library(readxl)
library(lubridate)

source("paths.R")
source("estimator.R")
```


# Main Effect Analysis
## Main Results

```{r, echo = FALSE, warning=FALSE, message = FALSE}
load(file.path(path_staged_data, "dat_analysis.RData"))

# This step might appear unnecessary, but is needed since
# dat_analysis is both a tibble and a data frame
# but code in estimator.R does not work with tibbles
# The call to as.data.frame() has the effect of making
# dat_analysis of class data frame but not of class tibble
dat_analysis <- as.data.frame(dat_analysis)
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt1 -- "No. of participant-decision points excluded due to the fact that participants did not select their preferred Product or Charity at baseline"
cnt1 <- dat_analysis %>% 
  filter(exclude_from_all == 1) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# The software expects that intervention assignment is coded as numeric, 
# and not character type
dat_analysis <- dat_analysis %>% 
  filter(exclude_from_all == 0) %>% 
  mutate(randassign_invite = case_when(
    randassign_invite == "Product" ~ 1,
    randassign_invite == "Charity" ~ 0,
    TRUE ~ NA_real_))
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt2 -- "No. of participant-decision points excluded due to the fact that participants had missing values in any of the covariates utilized in the noise reduction model"
cnt2 <- dat_analysis %>% 
  filter(did_not_report_primary_analysis_vars == 1) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Data preparation steps for primary analysis
these_vars <- c("tot_days_with_any_drinks", 
                "typical_num_drinks_per_day",
                "is_female",
                "is_white_only",
                "days_elapsed_since_entering")

dat_primary_analysis <- dat_analysis %>%
  # Drop participants who had any missing data in these_vars
  filter(did_not_report_primary_analysis_vars == 0) %>%
  select(participant_id, 
         decision_point, 
         randassign_invite, 
         coinflip, 
         Y_delta47,
         all_of(these_vars),
         sm_flagged, randtime_invite_hrts)
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt3 -- "No of participant-decision points excluded due to the fact that these participant-decision points came immediately after (i.e., time t+1) a decision point (i.e., time t) where the participant reported heavy drinking and hence were eligible for randomization (i.e., at time t+1). However, these participant-decision points did not have a record of the participant's randomization assignment present in the data."
cnt3 <- dat_primary_analysis %>% 
  filter(!(is.na(sm_flagged) & is.na(randtime_invite_hrts))) %>%
  filter(coinflip==0) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt4 -- "No. of participant-decision points excluded due to these participant-decision points not having a recorded randomization assignment at participant-decision points in which should have been randomized"
cnt4 <- dat_primary_analysis %>% 
  filter(is.na(sm_flagged) & is.na(randtime_invite_hrts)) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# How many participants and decision points will be used to estimate the treatment effect?
tab_summary_stats_H1 <- dat_primary_analysis %>%
  filter(coinflip==1) %>%
  group_by(decision_point) %>%
  summarise(count_randomized = n()) %>%
  mutate(excluded = 591 - count_randomized)

colnames(tab_summary_stats_H1) <- c("Decision Point", "Total No. Participants Included in Analysis",  "Total No. Participants Excluded from Analysis")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
list_results_H1 <- binary_outcome_moderated_effect(dta = dat_primary_analysis, 
                                                   control_var = c("tot_days_with_any_drinks", 
                                                                   "typical_num_drinks_per_day", 
                                                                   "is_white_only",
                                                                   "is_female",
                                                                   "days_elapsed_since_entering"),
                                                   moderator = NULL,
                                                   id_var = "participant_id",
                                                   day_var = "decision_point",
                                                   trt_var = "randassign_invite",
                                                   outcome_var = "Y_delta47",
                                                   avail_var = "coinflip",
                                                   prob_treatment = 1/2,
                                                   significance_level = 0.05)


significance_level <- 0.05
p <- list_results_H1[["dims"]]$p
q <- list_results_H1[["dims"]]$q
n <- list_results_H1[["sample_size"]]
all_estimates <- c(list_results_H1[["alpha_hat"]], list_results_H1[["beta_hat"]])
all_std_err <- c(list_results_H1[["alpha_se_ssa"]], list_results_H1[["beta_se_ssa"]])
test_stat <- all_estimates / all_std_err
critical_value <- qt(1 - significance_level/2, df = n - p - q) # two-sided
p_val <- lapply(test_stat, function(x){
  out <- 2 * pt(abs(x), df = n - p - q, lower.tail = FALSE) # two-sided
  return(out)
})
p_val <- do.call(rbind, p_val)

dat_results_H1 <- data.frame(estimate = all_estimates,
                             std_err = all_std_err,
                             p = p_val,
                             LB95 = all_estimates - critical_value*all_std_err,
                             UB95 = all_estimates + critical_value*all_std_err)

dat_results_H1 <- round(dat_results_H1, digits = 3)
row.names(dat_results_H1) <- c("Intercept", 
                               "No. of Days with any drinks", 
                               "No. of Drinks per day", 
                               "White (1=Yes, 0=otherwise)", 
                               "Female (1=Yes, 0=otherwise)",
                               "No. of Days elapsed since entering",
                               "beta")
colnames(dat_results_H1) <- c("est","SE","p","95%CI: LB","95%CI: UB")
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
list_results <- list_results_H1

# Calculate estimates on risk ratio scale
est_beta <- list_results[["beta_hat"]]
exp_estimates <- exp(est_beta)

# Calculate 95% CI on risk ratio scale
est_covmat_beta <- list_results[["varcov_ssa"]][1,1]
var_rr <- (exp_estimates) %*% est_covmat_beta %*% t(exp_estimates)
stderr_rr <- sqrt(var_rr)
rrLB95 <- exp(est_beta) - critical_value * stderr_rr
rrUB95 <- exp(est_beta) + critical_value * stderr_rr

# Collect results into a data frame
dat_exp_results_H1 <- data.frame(exp_estimates = exp_estimates,
                                 rrLB95 = rrLB95,
                                 rrUB95 = rrUB95)
dat_exp_results_H1 <- round(dat_exp_results_H1, digits = 3)
row.names(dat_exp_results_H1) <- c("exp(beta)")
colnames(dat_exp_results_H1) <- c("est","95%CI: LB","95%CI: UB")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
kable(tab_summary_stats_H1, format="latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = c("HOLD_position", "scale_down"))

kable(dat_results_H1, format="latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = c("HOLD_position")) %>% 
  pack_rows("Control Covariates", 1, q) %>% 
  pack_rows("Causal", q+1, q+p)

kable(dat_exp_results_H1, format="latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = c("HOLD_position"))
```


\newpage

## Appendix: Participants excluded from analyses -- breakdown by decision point and rationale

```{r, echo=FALSE, warning=FALSE, message=FALSE}
colnames(cnt1) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt2) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt3) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt4) <- c("Decision Point", "Number of Participants Excluded")
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
kable(cnt1, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to the fact that participants did not select their preferred Product or Charity at baseline") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt2, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to the fact that participants had missing values in any of the covariates utilized in the noise reduction model") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt3, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to these participant-decision points not having a recorded randomization assignment at participant-decision points in which should have been randomized") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt4, format="latex", booktabs=TRUE, caption = "No of participant-decision points excluded due to the fact that these participant-decision points came immediately after (i.e., time t+1) a decision point (i.e., time t) where the participant reported heavy drinking and hence were eligible for randomization (i.e., at time t+1). However, these participant-decision points did not have a record of the participant's randomization assignment present in the data.") %>% 
  kable_styling(latex_options = c("HOLD_position"))
```

\newpage

# Moderation Analysis
## Main Results

```{r, echo = FALSE, warning=FALSE, message = FALSE}
load(file.path(path_staged_data, "dat_analysis.RData"))

# This step might appear unnecessary, but is needed since
# dat_analysis is both a tibble and a data frame
# but code in estimator.R does not work with tibbles
# The call to as.data.frame() has the effect of making
# dat_analysis of class data frame but not of class tibble
dat_analysis <- as.data.frame(dat_analysis)
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt1 -- "No. of participant-decision points excluded due to the fact that participants did not select their preferred Product or Charity at baseline"
cnt1 <- dat_analysis %>% 
  filter(exclude_from_all == 1) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# The software expects that intervention assignment is coded as numeric, 
# and not character type
dat_analysis <- dat_analysis %>% 
  filter(exclude_from_all == 0) %>% 
  mutate(randassign_invite = case_when(
    randassign_invite == "Product" ~ 1,
    randassign_invite == "Charity" ~ 0,
    TRUE ~ NA_real_))
```


```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt2 -- "No. of participant-decision points excluded due to the fact that participants had missing values in any of the covariates utilized in the noise reduction model and moderators"
cnt2 <- dat_analysis %>% 
  filter(did_not_report_secondary_analysis_vars == 1) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Data preparation steps for secondary analysis
these_vars <- c("tot_days_with_any_drinks", 
                "typical_num_drinks_per_day",
                "is_female",
                "is_white_only",
                "days_elapsed_since_entering",
                "baseline_anxiety", 
                "baseline_depression", 
                "baseline_stress")

dat_secondary_analysis <- dat_analysis %>%
  # Drop participants who had any missing data in these_vars
  filter(did_not_report_secondary_analysis_vars == 0) %>%
  select(participant_id, 
         decision_point, 
         randassign_invite, 
         coinflip, 
         Y_delta47,
         all_of(these_vars),
         sm_flagged, randtime_invite_hrts)
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt3 -- "No of participant-decision points excluded due to the fact that these participant-decision points came immediately after (i.e., time t+1) a decision point (i.e., time t) where the participant reported heavy drinking and hence were eligible for randomization (i.e., at time t+1). However, these participant-decision points did not have a record of the participant's randomization assignment present in the data."
cnt3 <- dat_secondary_analysis %>% 
  filter(!(is.na(sm_flagged) & is.na(randtime_invite_hrts))) %>%
  filter(coinflip==0) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
# Count step-by-step how many participants we are excluding per decision point
# cnt4 -- "No. of participant-decision points excluded due to these participant-decision points not having a recorded randomization assignment at participant-decision points in which should have been randomized"
cnt4 <- dat_secondary_analysis %>% 
  filter(is.na(sm_flagged) & is.na(randtime_invite_hrts)) %>% 
  group_by(decision_point) %>%
  summarise(num_participants = n(), .groups = "keep")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# How many participants and decision points will be used to estimate the treatment effect?
tab_summary_stats_H2 <- dat_secondary_analysis %>%
    filter(coinflip==1) %>%
    group_by(decision_point) %>%
    summarise(count_randomized = n()) %>%
  mutate(excluded = 591 - count_randomized)

colnames(tab_summary_stats_H2) <- c("Decision Point", "Total No. Participants Included in Analysis",  "Total No. Participants Excluded from Analysis")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
list_results_H2 <- binary_outcome_moderated_effect(dta = dat_secondary_analysis, 
                                                   control_var = c("tot_days_with_any_drinks", 
                                                                   "typical_num_drinks_per_day", 
                                                                   "is_white_only",
                                                                   "is_female",
                                                                   "days_elapsed_since_entering"),
                                                   moderator = c("baseline_anxiety", 
                                                                 "baseline_depression", 
                                                                 "baseline_stress"),
                                                   id_var = "participant_id",
                                                   day_var = "decision_point",
                                                   trt_var = "randassign_invite",
                                                   outcome_var = "Y_delta47",
                                                   avail_var = "coinflip",
                                                   prob_treatment = 1/2,
                                                   significance_level = 0.05)


significance_level <- 0.05
p <- list_results_H2[["dims"]]$p
q <- list_results_H2[["dims"]]$q
n <- list_results_H2[["sample_size"]]
all_estimates <- c(list_results_H2[["alpha_hat"]], list_results_H2[["beta_hat"]])
all_std_err <- c(list_results_H2[["alpha_se_ssa"]], list_results_H2[["beta_se_ssa"]])
test_stat <- all_estimates / all_std_err
critical_value <- qt(1 - significance_level/2, df = n - p - q) # two-sided
p_val <- lapply(test_stat, function(x){
  out <- 2 * pt(abs(x), df = n - p - q, lower.tail = FALSE) # two-sided
  return(out)
})
p_val <- do.call(rbind, p_val)

dat_results_H2 <- data.frame(estimate = all_estimates,
                             std_err = all_std_err,
                             p = p_val,
                             LB95 = all_estimates - critical_value*all_std_err,
                             UB95 = all_estimates + critical_value*all_std_err)

dat_results_H2 <- round(dat_results_H2, digits = 3)
row.names(dat_results_H2) <- c("Intercept", 
                               "No. of Days with any drinks", 
                               "No. of Drinks per day", 
                               "White (1=Yes, 0=otherwise)", 
                               "Female (1=Yes, 0=otherwise)",
                               "No. of Days elapsed since entering",
                               "beta0",
                               "beta1 (Coefficient for treatment x baseline anxiety)",
                               "beta2 (Coefficient for treatment x baseline depression)",
                               "beta3 (Coefficient for treatment x baseline stress)")

colnames(dat_results_H2) <- c("est","SE","p","95%CI: LB","95%CI: UB")
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
kable(tab_summary_stats_H2, format="latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = c("HOLD_position", "scale_down"))

kable(dat_results_H2, format="latex", booktabs=TRUE) %>% 
  kable_styling(latex_options = c("HOLD_position")) %>% 
  pack_rows("Control Covariates", 1, q) %>% 
  pack_rows("Causal", q+1, q+p)
```

\newpage

## Appendix: Participants excluded from analyses -- breakdown by decision point and rationale

```{r, echo=FALSE, warning=FALSE, message=FALSE}
colnames(cnt1) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt2) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt3) <- c("Decision Point", "Number of Participants Excluded")
colnames(cnt4) <- c("Decision Point", "Number of Participants Excluded")
```


```{r, echo=FALSE, warning=FALSE, message=FALSE}
kable(cnt1, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to the fact that participants did not select their preferred Product or Charity at baseline") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt2, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to the fact that participants had missing values in any of the covariates utilized in the noise reduction model and moderators") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt3, format="latex", booktabs=TRUE, caption = "No. of participant-decision points excluded due to these participant-decision points not having a recorded randomization assignment at participant-decision points in which should have been randomized") %>% 
  kable_styling(latex_options = c("HOLD_position"))

kable(cnt4, format="latex", booktabs=TRUE, caption = "No of participant-decision points excluded due to the fact that these participant-decision points came immediately after (i.e., time t+1) a decision point (i.e., time t) where the participant reported heavy drinking and hence were eligible for randomization (i.e., at time t+1). However, these participant-decision points did not have a record of the participant's randomization assignment present in the data.") %>% 
  kable_styling(latex_options = c("HOLD_position"))
```

