---
title: "Results"
author: |
    |
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
output: 
  pdf_document:
    number_sections: TRUE
---

```{r, echo = FALSE, message = FALSE}
library(dplyr)
library(readxl)

source("paths.R")

source(file.path("run-analysis-exploratory-04.R"))
```

# Summary Statistics

```{r}
print(dat_summary_N)
```


```{r}
print(dat_summary_p)
```


```{r}
print(table01)
```

```{r}
print(table02)
```

```{r}
print(table03)
```

```{r}
print(table04)
```


# Outcome: Y=1 if NOT classified as non-responder by 1st decision point; Y=0 otherwise

```{r}
summary(mod_not_flagged_by_01a)
```

```{r}
summary(mod_not_flagged_by_01b)
```

# Outcome: Y=1 if NOT classified as non-responder by 2nd decision point; Y=0 otherwise

```{r}
summary(mod_not_flagged_by_02a)
```

```{r}
summary(mod_not_flagged_by_02b)
```


# Outcome: Y=1 if NOT classified as non-responder by 3rd decision point; Y=0 otherwise

```{r}
summary(mod_not_flagged_by_03a)
```

```{r}
summary(mod_not_flagged_by_03b)
```


# Outcome: Y=1 if NOT classified as non-responder by 4th decision point; Y=0 otherwise

```{r}
summary(mod_not_flagged_by_04a)
```

```{r}
summary(mod_not_flagged_by_04b)
```




