---
title: "Results"
author: |
    |
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
output: 
  pdf_document:
    number_sections: TRUE
---

```{r, echo = FALSE, message = FALSE}
library(dplyr)
library(readxl)

path_input_data <- Sys.getenv("path_input_data")
path_staged_data <- Sys.getenv("path_staged_data")

source(file.path("run-analysis-main.R"))
```

```{r, echo = FALSE}
dat_analysis %>%
  filter(coinflip==1) %>%
  group_by(decision_point) %>%
  summarise(minimum_hrs_elapsed = min(hrs_elapsed_invite_to_first_reminder, na.rm=TRUE),
            maximum_hrs_elapsed = max(hrs_elapsed_invite_to_first_reminder, na.rm=TRUE))
```

\newpage

```{r, echo = FALSE}
dat_response_probs <- dat_analysis %>%
  filter(coinflip == 1) %>%
  group_by(decision_point) %>%
  summarise(n_delta47 = sum(Y_delta47, na.rm=TRUE),
            tot = n())

dat_response_probs <- dat_response_probs %>%
  mutate(percent_delta47 = n_delta47/tot)

print(dat_response_probs)
```


\newpage

Treatment indicator was coded as '1' for 'Product' and '0' for 'Charity'.

```{r}
print(dat_results_H1)
```

```{r}
print(dat_results_H2)
```



\newpage

```{r, echo = FALSE}
dat_analysis <- dat_analysis %>%
  mutate(is_dp_early = if_else(decision_point==1 | decision_point==2, 1, 0),
         is_dp_late = if_else(decision_point==3 | decision_point==4, 1, 0))
```


```{r, echo=FALSE}
list_results_supp <- binary_outcome_moderated_effect(dta = dat_analysis, 
                                                   control_var = c("tot_days_with_any_drinks", 
                                                                   "typical_num_drinks_per_day", 
                                                                   "is_white",
                                                                   "is_female", 
                                                                   "is_male", 
                                                                   "days_elapsed_since_entering"),
                                                   moderator = c("is_dp_early"),
                                                   id_var = "participant_id",
                                                   day_var = "decision_point",
                                                   trt_var = "randassign_invite",
                                                   outcome_var = "Y_delta47",
                                                   avail_var = "coinflip",
                                                   prob_treatment = 1/2,
                                                   significance_level = 0.05)


significance_level <- 0.05
p <- list_results_supp[["dims"]]$p
q <- list_results_supp[["dims"]]$q
n <- list_results_supp[["sample_size"]]
all_estimates <- c(list_results_supp[["alpha_hat"]], list_results_supp[["beta_hat"]])
all_std_err <- c(list_results_supp[["alpha_se_ssa"]], list_results_supp[["beta_se_ssa"]])
test_stat <- all_estimates / all_std_err
critical_value <- qt(1 - significance_level/2, df = n - p - q) # two-sided
p_val <- lapply(test_stat, function(x){
  out <- 2 * pt(abs(x), df = n - p - q, lower.tail = FALSE) # two-sided
  return(out)
})
p_val <- do.call(rbind, p_val)

dat_results_supp <- data.frame(estimate = all_estimates,
                             std_err = all_std_err,
                             p = p_val)
dat_results_supp <- round(dat_results_supp, digits = 3)
row.names(dat_results_supp) <- c("Intercept", 
                               "No. of Days with any drinks", 
                               "No. of Drinks per day", 
                               "White (1=Yes, 0=otherwise)", 
                               "Female (1=Yes, 0=otherwise)",
                               "Male (1=Yes, 0=otherwise)",
                               "No. of Days elapsed since entering",
                               "beta0",
                               "beta1 (coefficient for is_dp_early)")
```


```{r}
print(dat_results_supp)
```


Above, the variable is_dp_early is equal to 1 if decision point is either 1 or 2; the variable is_dp_early is equal to 0 if decision point is either 3 or 4. 
















