---
title: "Summary Statistics"
author: |
    |
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
output: 
  pdf_document:
    number_sections: TRUE
---

```{r, echo = FALSE, message = FALSE}
library(dplyr)
library(readxl)

source("paths.R")

###############################################################################
# Load data for analysis after executing run-data-curation-pipeline.R
###############################################################################

load(file.path(path_staged_data, "dat_analysis.RData"))

###############################################################################
# For each decision point, check the number of participants whom to include
# in the estimation of the treatment effect
###############################################################################

dat_include <- dat_analysis %>%
  group_by(decision_point) %>%
  summarise(percent_included = mean(coinflip),
            tot = nrow(coinflip))

###############################################################################
# Check empirical prob of being randomized to each intervention option
###############################################################################

dat_rand_probs_invite <- dat_analysis %>%
  filter(coinflip == 1) %>%
  group_by(decision_point) %>%
  summarise(n_charity = sum(randassign_invite == "Charity", na.rm=TRUE),
            n_product = sum(randassign_invite == "Product", na.rm=TRUE))

dat_rand_probs_invite <- dat_rand_probs_invite %>%
  mutate(prob_charity = n_charity/(n_charity + n_product))

###############################################################################
# Check hours elapsed between invite to first reminder
###############################################################################

dat_hrs_elapsed <- dat_analysis %>%
  filter(coinflip==1) %>%
  group_by(decision_point) %>%
  summarise(minimum_hrs_elapsed = min(hrs_elapsed_invite_to_first_reminder, na.rm=TRUE),
            maximum_hrs_elapsed = max(hrs_elapsed_invite_to_first_reminder, na.rm=TRUE))

###############################################################################
# Check empirical prob of survey completion
###############################################################################

dat_response_probs <- dat_analysis %>%
  filter(coinflip == 1) %>%
  group_by(decision_point) %>%
  summarise(n_delta47 = sum(Y_delta47, na.rm=TRUE),
            tot = n())

dat_response_probs <- dat_response_probs %>%
  mutate(percent_delta47 = n_delta47/tot)
```



```{r}
print(dat_include)
```


```{r}
print(dat_rand_probs_invite)
```


```{r}
print(dat_hrs_elapsed)
```


```{r}
print(dat_response_probs)
```




